apiVersion: v1
kind: Service
metadata:
  name: stockportfolio-service
  labels:
    app: stockportfolio
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: stockportfolio
